//
// l8tunnel control protocol.
//
// Every message on the control stream (the first mux stream the agent opens)
// is a length-prefixed ControlMessage. Every data stream the relay opens
// starts with a single length-prefixed StreamOpen, followed by raw bytes.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: l8tunnel.proto

package l8tunnel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelType int32

const (
	TunnelType_TUNNEL_TYPE_UNSPECIFIED TunnelType = 0
	TunnelType_TUNNEL_TYPE_HTTP        TunnelType = 1 // TLS terminated at the relay, routed by Host header
	TunnelType_TUNNEL_TYPE_TLS         TunnelType = 2 // TLS passthrough, routed by SNI
	TunnelType_TUNNEL_TYPE_TCP         TunnelType = 3 // raw TCP on a dedicated public port
	TunnelType_TUNNEL_TYPE_SSH         TunnelType = 4 // TCP preset, default local target :22
)

// Enum value maps for TunnelType.
var (
	TunnelType_name = map[int32]string{
		0: "TUNNEL_TYPE_UNSPECIFIED",
		1: "TUNNEL_TYPE_HTTP",
		2: "TUNNEL_TYPE_TLS",
		3: "TUNNEL_TYPE_TCP",
		4: "TUNNEL_TYPE_SSH",
	}
	TunnelType_value = map[string]int32{
		"TUNNEL_TYPE_UNSPECIFIED": 0,
		"TUNNEL_TYPE_HTTP":        1,
		"TUNNEL_TYPE_TLS":         2,
		"TUNNEL_TYPE_TCP":         3,
		"TUNNEL_TYPE_SSH":         4,
	}
)

func (x TunnelType) Enum() *TunnelType {
	p := new(TunnelType)
	*p = x
	return p
}

func (x TunnelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelType) Descriptor() protoreflect.EnumDescriptor {
	return file_l8tunnel_proto_enumTypes[0].Descriptor()
}

func (TunnelType) Type() protoreflect.EnumType {
	return &file_l8tunnel_proto_enumTypes[0]
}

func (x TunnelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelType.Descriptor instead.
func (TunnelType) EnumDescriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{0}
}

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED             ErrorCode = 0
	ErrorCode_ERROR_CODE_UNAUTHORIZED            ErrorCode = 1
	ErrorCode_ERROR_CODE_UNSUPPORTED_VERSION     ErrorCode = 2
	ErrorCode_ERROR_CODE_INVALID_REQUEST         ErrorCode = 3
	ErrorCode_ERROR_CODE_UNSUPPORTED_TUNNEL_TYPE ErrorCode = 4
	ErrorCode_ERROR_CODE_NAME_TAKEN              ErrorCode = 5
	ErrorCode_ERROR_CODE_PORT_NOT_ALLOWED        ErrorCode = 6
	ErrorCode_ERROR_CODE_PORT_UNAVAILABLE        ErrorCode = 7
	ErrorCode_ERROR_CODE_FORBIDDEN               ErrorCode = 8 // the token's policy doesn't allow the request
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_UNAUTHORIZED",
		2: "ERROR_CODE_UNSUPPORTED_VERSION",
		3: "ERROR_CODE_INVALID_REQUEST",
		4: "ERROR_CODE_UNSUPPORTED_TUNNEL_TYPE",
		5: "ERROR_CODE_NAME_TAKEN",
		6: "ERROR_CODE_PORT_NOT_ALLOWED",
		7: "ERROR_CODE_PORT_UNAVAILABLE",
		8: "ERROR_CODE_FORBIDDEN",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":             0,
		"ERROR_CODE_UNAUTHORIZED":            1,
		"ERROR_CODE_UNSUPPORTED_VERSION":     2,
		"ERROR_CODE_INVALID_REQUEST":         3,
		"ERROR_CODE_UNSUPPORTED_TUNNEL_TYPE": 4,
		"ERROR_CODE_NAME_TAKEN":              5,
		"ERROR_CODE_PORT_NOT_ALLOWED":        6,
		"ERROR_CODE_PORT_UNAVAILABLE":        7,
		"ERROR_CODE_FORBIDDEN":               8,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_l8tunnel_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_l8tunnel_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{1}
}

type Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtocolVersion uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Token           string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	AgentId         string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentVersion    string `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Os              string `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Arch            string `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`
}

func (x *Hello) Reset() {
	*x = Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8tunnel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_l8tunnel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Hello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Hello) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type Welcome struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId           string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	HeartbeatIntervalMs int64  `protobuf:"varint,2,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8tunnel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_l8tunnel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *Welcome) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Welcome) GetHeartbeatIntervalMs() int64 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=l8tunnel.ErrorCode" json:"code,omitempty"`
	Message string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8tunnel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_l8tunnel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TunnelSpec never carries the local target: the agent keeps the
// tunnel -> target mapping, so the relay can't make it dial anything else.
type TunnelSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type       TunnelType    `protobuf:"varint,2,opt,name=type,proto3,enum=l8tunnel.TunnelType" json:"type,omitempty"`
	PublicPort uint32        `protobuf:"varint,3,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"` // TCP/SSH only; 0 = allocate from the relay's range
	Access     *AccessPolicy `protobuf:"bytes,4,opt,name=access,proto3" json:"access,omitempty"`
	Domains    []string      `protobuf:"bytes,5,rep,name=domains,proto3" json:"domains,omitempty"` // HTTP/TLS only: custom domains (CNAME to the relay)
}

func (x *TunnelSpec) Reset() {
	*x = TunnelSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8tunnel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunnelSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelSpec) ProtoMessage() {}

func (x *TunnelSpec) ProtoReflect() protoreflect.Message {
	mi := &file_l8tunnel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelSpec.ProtoReflect.Descriptor instead.
func (*TunnelSpec) Descriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *TunnelSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TunnelSpec) GetType() TunnelType {
	if x != nil {
		return x.Type
	}
	return TunnelType_TUNNEL_TYPE_UNSPECIFIED
}

func (x *TunnelSpec) GetPublicPort() uint32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

func (x *TunnelSpec) GetAccess() *AccessPolicy {
	if x != nil {
		return x.Access
	}
	return nil
}

func (x *TunnelSpec) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

// AccessPolicy restricts who can use a tunnel; the relay enforces it.
type AccessPolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllowIps          []string     `protobuf:"bytes,1,rep,name=allow_ips,json=allowIps,proto3" json:"allow_ips,omitempty"`                              // CIDRs or addresses; empty = everyone
	DenyIps           []string     `protobuf:"bytes,2,rep,name=deny_ips,json=denyIps,proto3" json:"deny_ips,omitempty"`                                 // CIDRs or addresses; deny wins
	BasicUsers        []*BasicUser `protobuf:"bytes,3,rep,name=basic_users,json=basicUsers,proto3" json:"basic_users,omitempty"`                        // HTTP tunnels only
	AccessTokenSha256 []byte       `protobuf:"bytes,4,opt,name=access_token_sha256,json=accessTokenSha256,proto3" json:"access_token_sha256,omitempty"` // TCP/SSH only: mode B clients must
	// present the token (no mode A port)
	Oidc *OIDCPolicy `protobuf:"bytes,5,opt,name=oidc,proto3" json:"oidc,omitempty"` // HTTP only: sign in through a provider
}

func (x *AccessPolicy) Reset() {
	*x = AccessPolicy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8tunnel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessPolicy) ProtoMessage() {}

func (x *AccessPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_l8tunnel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessPolicy.ProtoReflect.Descriptor instead.
func (*AccessPolicy) Descriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *AccessPolicy) GetAllowIps() []string {
	if x != nil {
		return x.AllowIps
	}
	return nil
}

func (x *AccessPolicy) GetDenyIps() []string {
	if x != nil {
		return x.DenyIps
	}
	return nil
}

func (x *AccessPolicy) GetBasicUsers() []*BasicUser {
	if x != nil {
		return x.BasicUsers
	}
	return nil
}

func (x *AccessPolicy) GetAccessTokenSha256() []byte {
	if x != nil {
		return x.AccessTokenSha256
	}
	return nil
}

func (x *AccessPolicy) GetOidc() *OIDCPolicy {
	if x != nil {
		return x.Oidc
	}
	return nil
}

// OIDCPolicy requires an OIDC login (with a provider configured on the
// relay) and restricts who may pass; at least one allow entry is required.
type OIDCPolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provider     string   `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	AllowEmails  []string `protobuf:"bytes,2,rep,name=allow_emails,json=allowEmails,proto3" json:"allow_emails,omitempty"`
	AllowDomains []string `protobuf:"bytes,3,rep,name=allow_domains,json=allowDomains,proto3" json:"allow_domains,omitempty"`
}

func (x *OIDCPolicy) Reset() {
	*x = OIDCPolicy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8tunnel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OIDCPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDCPolicy) ProtoMessage() {}

func (x *OIDCPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_l8tunnel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OIDCPolicy.ProtoReflect.Descriptor instead.
func (*OIDCPolicy) Descriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *OIDCPolicy) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *OIDCPolicy) GetAllowEmails() []string {
	if x != nil {
		return x.AllowEmails
	}
	return nil
}

func (x *OIDCPolicy) GetAllowDomains() []string {
	if x != nil {
		return x.AllowDomains
	}
	return nil
}

type BasicUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username   string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	BcryptHash string `protobuf:"bytes,2,opt,name=bcrypt_hash,json=bcryptHash,proto3" json:"bcrypt_hash,omitempty"`
}

func (x *BasicUser) Reset() {
	*x = BasicUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8tunnel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicUser) ProtoMessage() {}

func (x *BasicUser) ProtoReflect() protoreflect.Message {
	mi := &file_l8tunnel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicUser.ProtoReflect.Descriptor instead.
func (*BasicUser) Descriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *BasicUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicUser) GetBcryptHash() string {
	if x != nil {
		return x.BcryptHash
	}
	return ""
}

type Register struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tunnels []*TunnelSpec `protobuf:"bytes,1,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
}

func (x *Register) Reset() {
	*x = Register{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8tunnel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_l8tunnel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{7}
}

func (x *Register) GetTunnels() []*TunnelSpec {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

type Endpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TunnelId      string     `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Name          string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          TunnelType `protobuf:"varint,3,opt,name=type,proto3,enum=l8tunnel.TunnelType" json:"type,omitempty"`
	PublicAddress string     `protobuf:"bytes,4,opt,name=public_address,json=publicAddress,proto3" json:"public_address,omitempty"` // mode A: <public_host>:<public_port>
	PublicPort    uint32     `protobuf:"varint,5,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	Hostname      string     `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"` // mode B: TLS SNI host, <name>.<base_domain>
	Domains       []string   `protobuf:"bytes,7,rep,name=domains,proto3" json:"domains,omitempty"`   // custom domains served by this tunnel
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8tunnel_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_l8tunnel_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{8}
}

func (x *Endpoint) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *Endpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Endpoint) GetType() TunnelType {
	if x != nil {
		return x.Type
	}
	return TunnelType_TUNNEL_TYPE_UNSPECIFIED
}

func (x *Endpoint) GetPublicAddress() string {
	if x != nil {
		return x.PublicAddress
	}
	return ""
}

func (x *Endpoint) GetPublicPort() uint32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

func (x *Endpoint) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Endpoint) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

type Registered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoints []*Endpoint `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
}

func (x *Registered) Reset() {
	*x = Registered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8tunnel_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Registered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registered) ProtoMessage() {}

func (x *Registered) ProtoReflect() protoreflect.Message {
	mi := &file_l8tunnel_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registered.ProtoReflect.Descriptor instead.
func (*Registered) Descriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{9}
}

func (x *Registered) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce        uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	SentUnixNano int64  `protobuf:"varint,2,opt,name=sent_unix_nano,json=sentUnixNano,proto3" json:"sent_unix_nano,omitempty"`
	LastRttUs    int64  `protobuf:"varint,3,opt,name=last_rtt_us,json=lastRttUs,proto3" json:"last_rtt_us,omitempty"` // the agent's last measured round trip (metrics)
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8tunnel_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_l8tunnel_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{10}
}

func (x *Ping) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Ping) GetSentUnixNano() int64 {
	if x != nil {
		return x.SentUnixNano
	}
	return 0
}

func (x *Ping) GetLastRttUs() int64 {
	if x != nil {
		return x.LastRttUs
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce        uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	SentUnixNano int64  `protobuf:"varint,2,opt,name=sent_unix_nano,json=sentUnixNano,proto3" json:"sent_unix_nano,omitempty"`
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8tunnel_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_l8tunnel_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{11}
}

func (x *Pong) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Pong) GetSentUnixNano() int64 {
	if x != nil {
		return x.SentUnixNano
	}
	return 0
}

type ControlMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Body:
	//
	//	*ControlMessage_Hello
	//	*ControlMessage_Welcome
	//	*ControlMessage_Error
	//	*ControlMessage_Register
	//	*ControlMessage_Registered
	//	*ControlMessage_Ping
	//	*ControlMessage_Pong
	Body isControlMessage_Body `protobuf_oneof:"body"`
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8tunnel_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_l8tunnel_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{12}
}

func (m *ControlMessage) GetBody() isControlMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *ControlMessage) GetHello() *Hello {
	if x, ok := x.GetBody().(*ControlMessage_Hello); ok {
		return x.Hello
	}
	return nil
}

func (x *ControlMessage) GetWelcome() *Welcome {
	if x, ok := x.GetBody().(*ControlMessage_Welcome); ok {
		return x.Welcome
	}
	return nil
}

func (x *ControlMessage) GetError() *Error {
	if x, ok := x.GetBody().(*ControlMessage_Error); ok {
		return x.Error
	}
	return nil
}

func (x *ControlMessage) GetRegister() *Register {
	if x, ok := x.GetBody().(*ControlMessage_Register); ok {
		return x.Register
	}
	return nil
}

func (x *ControlMessage) GetRegistered() *Registered {
	if x, ok := x.GetBody().(*ControlMessage_Registered); ok {
		return x.Registered
	}
	return nil
}

func (x *ControlMessage) GetPing() *Ping {
	if x, ok := x.GetBody().(*ControlMessage_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *ControlMessage) GetPong() *Pong {
	if x, ok := x.GetBody().(*ControlMessage_Pong); ok {
		return x.Pong
	}
	return nil
}

type isControlMessage_Body interface {
	isControlMessage_Body()
}

type ControlMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ControlMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,2,opt,name=welcome,proto3,oneof"`
}

type ControlMessage_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type ControlMessage_Register struct {
	Register *Register `protobuf:"bytes,4,opt,name=register,proto3,oneof"`
}

type ControlMessage_Registered struct {
	Registered *Registered `protobuf:"bytes,5,opt,name=registered,proto3,oneof"`
}

type ControlMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,6,opt,name=ping,proto3,oneof"`
}

type ControlMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,7,opt,name=pong,proto3,oneof"`
}

func (*ControlMessage_Hello) isControlMessage_Body() {}

func (*ControlMessage_Welcome) isControlMessage_Body() {}

func (*ControlMessage_Error) isControlMessage_Body() {}

func (*ControlMessage_Register) isControlMessage_Body() {}

func (*ControlMessage_Registered) isControlMessage_Body() {}

func (*ControlMessage_Ping) isControlMessage_Body() {}

func (*ControlMessage_Pong) isControlMessage_Body() {}

// ConnectAuth is sent by "l8tunnel connect" right after the TLS handshake
// when the relay negotiated the connect-token ALPN (mode B tunnels that
// require an access token).
type ConnectAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
}

func (x *ConnectAuth) Reset() {
	*x = ConnectAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8tunnel_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectAuth) ProtoMessage() {}

func (x *ConnectAuth) ProtoReflect() protoreflect.Message {
	mi := &file_l8tunnel_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectAuth.ProtoReflect.Descriptor instead.
func (*ConnectAuth) Descriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{13}
}

func (x *ConnectAuth) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// ConnectAuthResult is the relay's answer to ConnectAuth; tunnel data
// follows only when ok is true.
type ConnectAuthResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *ConnectAuthResult) Reset() {
	*x = ConnectAuthResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8tunnel_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectAuthResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectAuthResult) ProtoMessage() {}

func (x *ConnectAuthResult) ProtoReflect() protoreflect.Message {
	mi := &file_l8tunnel_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectAuthResult.ProtoReflect.Descriptor instead.
func (*ConnectAuthResult) Descriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{14}
}

func (x *ConnectAuthResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type StreamOpen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TunnelId   string `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	ClientAddr string `protobuf:"bytes,2,opt,name=client_addr,json=clientAddr,proto3" json:"client_addr,omitempty"`
}

func (x *StreamOpen) Reset() {
	*x = StreamOpen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_l8tunnel_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOpen) ProtoMessage() {}

func (x *StreamOpen) ProtoReflect() protoreflect.Message {
	mi := &file_l8tunnel_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOpen.ProtoReflect.Descriptor instead.
func (*StreamOpen) Descriptor() ([]byte, []int) {
	return file_l8tunnel_proto_rawDescGZIP(), []int{15}
}

func (x *StreamOpen) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *StreamOpen) GetClientAddr() string {
	if x != nil {
		return x.ClientAddr
	}
	return ""
}

var File_l8tunnel_proto protoreflect.FileDescriptor

var file_l8tunnel_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6c, 0x38, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6c, 0x38, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0xac, 0x01, 0x0a, 0x05, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x63, 0x68, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x63, 0x68, 0x22, 0x5c, 0x0a, 0x07, 0x57, 0x65, 0x6c,
	0x63, 0x6f, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x15, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x13, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x4d, 0x73, 0x22, 0x4a, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x27, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13,
	0x2e, 0x6c, 0x38, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0xb5, 0x01, 0x0a, 0x0a, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53, 0x70,
	0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6c, 0x38, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e,
	0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x50, 0x6f, 0x72,
	0x74, 0x12, 0x2e, 0x0a, 0x06, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x38, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x06, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x22, 0xd6, 0x01, 0x0a, 0x0c,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x1b, 0x0a, 0x09,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x08, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x49, 0x70, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x65, 0x6e,
	0x79, 0x5f, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x6e,
	0x79, 0x49, 0x70, 0x73, 0x12, 0x34, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x38, 0x74, 0x75,
	0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0a,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x73, 0x68, 0x61, 0x32, 0x35,
	0x36, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x53, 0x68, 0x61, 0x32, 0x35, 0x36, 0x12, 0x28, 0x0a, 0x04, 0x6f, 0x69,
	0x64, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x38, 0x74, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x2e, 0x4f, 0x49, 0x44, 0x43, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x04,
	0x6f, 0x69, 0x64, 0x63, 0x22, 0x70, 0x0a, 0x0a, 0x4f, 0x49, 0x44, 0x43, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x21,
	0x0a, 0x0c, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x73, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x44,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x22, 0x48, 0x0a, 0x09, 0x42, 0x61, 0x73, 0x69, 0x63, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x62, 0x63, 0x72, 0x79, 0x70, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x63, 0x72, 0x79, 0x70, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x22, 0x3a, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x07,
	0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x6c, 0x38, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x07, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x22, 0xe3, 0x01, 0x0a,
	0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x75,
	0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6c, 0x38, 0x74, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x2e, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x73, 0x22, 0x3e, 0x0a, 0x0a, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64,
	0x12, 0x30, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x38, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x45,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x22, 0x62, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65,
	0x12, 0x24, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6e, 0x61,
	0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x65, 0x6e, 0x74, 0x55, 0x6e,
	0x69, 0x78, 0x4e, 0x61, 0x6e, 0x6f, 0x12, 0x1e, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x72,
	0x74, 0x74, 0x5f, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x61, 0x73,
	0x74, 0x52, 0x74, 0x74, 0x55, 0x73, 0x22, 0x42, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x6e, 0x69,
	0x78, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x65,
	0x6e, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x4e, 0x61, 0x6e, 0x6f, 0x22, 0xcf, 0x02, 0x0a, 0x0e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a,
	0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c,
	0x38, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52,
	0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x2d, 0x0a, 0x07, 0x77, 0x65, 0x6c, 0x63, 0x6f, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38, 0x74, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x2e, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x07, 0x77, 0x65,
	0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x38, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x30,
	0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x6c, 0x38, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x12, 0x36, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x38, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6c, 0x38, 0x74, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x24,
	0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6c,
	0x38, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04,
	0x70, 0x6f, 0x6e, 0x67, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x30, 0x0a, 0x0b,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x41, 0x75, 0x74, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x23,
	0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x02, 0x6f, 0x6b, 0x22, 0x4a, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4f, 0x70, 0x65,
	0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x2a,
	0x7e, 0x0a, 0x0a, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a,
	0x17, 0x54, 0x55, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x55,
	0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x48, 0x54, 0x54, 0x50, 0x10, 0x01,
	0x12, 0x13, 0x0a, 0x0f, 0x54, 0x55, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x54, 0x4c, 0x53, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x55, 0x4e, 0x4e, 0x45, 0x4c, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x43, 0x50, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x55,
	0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x53, 0x48, 0x10, 0x04, 0x2a,
	0xa7, 0x02, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a,
	0x16, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52,
	0x49, 0x5a, 0x45, 0x44, 0x10, 0x01, 0x12, 0x22, 0x0a, 0x1e, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f,
	0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54, 0x45, 0x44,
	0x5f, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x1e, 0x0a, 0x1a, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44,
	0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x03, 0x12, 0x26, 0x0a, 0x22, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x55, 0x50, 0x50, 0x4f,
	0x52, 0x54, 0x45, 0x44, 0x5f, 0x54, 0x55, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45,
	0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x5f, 0x54, 0x41, 0x4b, 0x45, 0x4e, 0x10, 0x05, 0x12, 0x1f, 0x0a,
	0x1b, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x50, 0x4f, 0x52, 0x54,
	0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x45, 0x44, 0x10, 0x06, 0x12, 0x1f,
	0x0a, 0x1b, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x50, 0x4f, 0x52,
	0x54, 0x5f, 0x55, 0x4e, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x07, 0x12,
	0x18, 0x0a, 0x14, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x46, 0x4f,
	0x52, 0x42, 0x49, 0x44, 0x44, 0x45, 0x4e, 0x10, 0x08, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2f, 0x6c, 0x38, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_l8tunnel_proto_rawDescOnce sync.Once
	file_l8tunnel_proto_rawDescData = file_l8tunnel_proto_rawDesc
)

func file_l8tunnel_proto_rawDescGZIP() []byte {
	file_l8tunnel_proto_rawDescOnce.Do(func() {
		file_l8tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(file_l8tunnel_proto_rawDescData)
	})
	return file_l8tunnel_proto_rawDescData
}

var file_l8tunnel_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_l8tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_l8tunnel_proto_goTypes = []interface{}{
	(TunnelType)(0),           // 0: l8tunnel.TunnelType
	(ErrorCode)(0),            // 1: l8tunnel.ErrorCode
	(*Hello)(nil),             // 2: l8tunnel.Hello
	(*Welcome)(nil),           // 3: l8tunnel.Welcome
	(*Error)(nil),             // 4: l8tunnel.Error
	(*TunnelSpec)(nil),        // 5: l8tunnel.TunnelSpec
	(*AccessPolicy)(nil),      // 6: l8tunnel.AccessPolicy
	(*OIDCPolicy)(nil),        // 7: l8tunnel.OIDCPolicy
	(*BasicUser)(nil),         // 8: l8tunnel.BasicUser
	(*Register)(nil),          // 9: l8tunnel.Register
	(*Endpoint)(nil),          // 10: l8tunnel.Endpoint
	(*Registered)(nil),        // 11: l8tunnel.Registered
	(*Ping)(nil),              // 12: l8tunnel.Ping
	(*Pong)(nil),              // 13: l8tunnel.Pong
	(*ControlMessage)(nil),    // 14: l8tunnel.ControlMessage
	(*ConnectAuth)(nil),       // 15: l8tunnel.ConnectAuth
	(*ConnectAuthResult)(nil), // 16: l8tunnel.ConnectAuthResult
	(*StreamOpen)(nil),        // 17: l8tunnel.StreamOpen
}
var file_l8tunnel_proto_depIdxs = []int32{
	1,  // 0: l8tunnel.Error.code:type_name -> l8tunnel.ErrorCode
	0,  // 1: l8tunnel.TunnelSpec.type:type_name -> l8tunnel.TunnelType
	6,  // 2: l8tunnel.TunnelSpec.access:type_name -> l8tunnel.AccessPolicy
	8,  // 3: l8tunnel.AccessPolicy.basic_users:type_name -> l8tunnel.BasicUser
	7,  // 4: l8tunnel.AccessPolicy.oidc:type_name -> l8tunnel.OIDCPolicy
	5,  // 5: l8tunnel.Register.tunnels:type_name -> l8tunnel.TunnelSpec
	0,  // 6: l8tunnel.Endpoint.type:type_name -> l8tunnel.TunnelType
	10, // 7: l8tunnel.Registered.endpoints:type_name -> l8tunnel.Endpoint
	2,  // 8: l8tunnel.ControlMessage.hello:type_name -> l8tunnel.Hello
	3,  // 9: l8tunnel.ControlMessage.welcome:type_name -> l8tunnel.Welcome
	4,  // 10: l8tunnel.ControlMessage.error:type_name -> l8tunnel.Error
	9,  // 11: l8tunnel.ControlMessage.register:type_name -> l8tunnel.Register
	11, // 12: l8tunnel.ControlMessage.registered:type_name -> l8tunnel.Registered
	12, // 13: l8tunnel.ControlMessage.ping:type_name -> l8tunnel.Ping
	13, // 14: l8tunnel.ControlMessage.pong:type_name -> l8tunnel.Pong
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_l8tunnel_proto_init() }
func file_l8tunnel_proto_init() {
	if File_l8tunnel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_l8tunnel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8tunnel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Welcome); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8tunnel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8tunnel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8tunnel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessPolicy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8tunnel_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OIDCPolicy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8tunnel_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8tunnel_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Register); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8tunnel_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Endpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8tunnel_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Registered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8tunnel_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8tunnel_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8tunnel_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8tunnel_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8tunnel_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectAuthResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_l8tunnel_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamOpen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_l8tunnel_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*ControlMessage_Hello)(nil),
		(*ControlMessage_Welcome)(nil),
		(*ControlMessage_Error)(nil),
		(*ControlMessage_Register)(nil),
		(*ControlMessage_Registered)(nil),
		(*ControlMessage_Ping)(nil),
		(*ControlMessage_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_l8tunnel_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_l8tunnel_proto_goTypes,
		DependencyIndexes: file_l8tunnel_proto_depIdxs,
		EnumInfos:         file_l8tunnel_proto_enumTypes,
		MessageInfos:      file_l8tunnel_proto_msgTypes,
	}.Build()
	File_l8tunnel_proto = out.File
	file_l8tunnel_proto_rawDesc = nil
	file_l8tunnel_proto_goTypes = nil
	file_l8tunnel_proto_depIdxs = nil
}
